import type { Category, Label, Task } from "./types";
import { daysFromNow, datetimeFromNow } from "@/lib/date";

export const seedLabels: Label[] = [
  { id: "work", name: "Work", tone: "pen" },
  { id: "personal", name: "Personal", tone: "marker" },
  { id: "errands", name: "Errands", tone: "gray" },
];

export const seedCategories: Category[] = [
  { id: "product", name: "Product", icon: "package", color: "blue" },
  { id: "design", name: "Design", icon: "palette", color: "cyan" },
  { id: "development", name: "Development", icon: "terminal", color: "green" },
  { id: "operations", name: "Operations", icon: "zap", color: "pink" },
  { id: "testing", name: "Testing", icon: "flask", color: "yellow" },
];

function monthDay(day: number, hour = 10): { due: string; iso: string } {
  const now = new Date();
  const date = new Date(now.getFullYear(), now.getMonth(), day, hour, 0, 0);
  const iso = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
  return { due: iso, iso: date.toISOString() };
}

function span(startDay: number, endDay: number) {
  return {
    startDate: monthDay(startDay).due,
    endDate: monthDay(endDay).due,
  };
}

export function createSeedTasks(): Task[] {
  const t = (daysAgo: number) => ({
    created: datetimeFromNow(-daysAgo, 9),
    updated: datetimeFromNow(-daysAgo, 14),
  });

  const m1 = t(12);
  const m2 = t(9);
  const m3 = t(7);
  const m4 = t(4);
  const m5 = t(3);
  const m6 = t(2);
  const m7 = t(1);
  const m8 = t(0);
  const m9 = t(0);
  const m10 = t(0);

  const today = new Date();
  const lastDay = new Date(
    today.getFullYear(),
    today.getMonth() + 1,
    0,
  ).getDate();
  const p1 = monthDay(1);
  const p2 = monthDay(2);
  const p4 = monthDay(4);
  const p7 = monthDay(7);
  const p9 = monthDay(9);
  const p10 = monthDay(10);
  const p12 = monthDay(12);
  const p13 = monthDay(13);
  const p14 = monthDay(14);
  const p15 = monthDay(15);
  const p16 = monthDay(16);
  const p17 = monthDay(17);
  const p19 = monthDay(19);
  const p20 = monthDay(20);
  const p21 = monthDay(21);
  const p22 = monthDay(22);
  const projectEnd = Math.min(24, lastDay);

  return [
    {
      id: "t1",
      title: "Pay electric bill",
      description: "",
      status: "todo",
      priority: "urgent",
      dueAt: daysFromNow(-1),
      completedAt: null,
      position: 1,
      createdAt: m5.created,
      updatedAt: m5.updated,
      labelIds: ["errands"],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(-1),
      endDate: daysFromNow(-1),
    },
    {
      id: "t2",
      title: "Finish homework",
      description: "Physics chapter 4 and the problem set at the end.",
      status: "todo",
      priority: "high",
      dueAt: daysFromNow(0),
      completedAt: null,
      position: 2,
      createdAt: m2.created,
      updatedAt: m2.updated,
      labelIds: ["work"],
      subtasks: [
        { id: "s1", title: "Read chapter 4", completed: true, position: 1 },
        { id: "s2", title: "Solve problem set", completed: false, position: 2 },
      ],
      categoryId: null,
      startDate: daysFromNow(0),
      endDate: daysFromNow(0),
    },
    {
      id: "t3",
      title: "Buy groceries",
      description: "",
      status: "todo",
      priority: "none",
      dueAt: daysFromNow(0),
      completedAt: null,
      position: 3,
      createdAt: m6.created,
      updatedAt: m6.updated,
      labelIds: ["errands"],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(0),
      endDate: daysFromNow(0),
    },
    {
      id: "t4",
      title: "Call John about Saturday",
      description: "",
      status: "todo",
      priority: "medium",
      dueAt: daysFromNow(1),
      completedAt: null,
      position: 4,
      createdAt: m1.created,
      updatedAt: m1.updated,
      labelIds: ["personal"],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(1),
      endDate: daysFromNow(1),
    },
    {
      id: "t5",
      title: "Review Q3 roadmap",
      description: "Read the draft, leave comments, send it back to the team.",
      status: "todo",
      priority: "high",
      dueAt: daysFromNow(4),
      completedAt: null,
      position: 5,
      createdAt: m4.created,
      updatedAt: m4.updated,
      labelIds: ["work"],
      subtasks: [
        { id: "s3", title: "Read the draft", completed: true, position: 1 },
        { id: "s4", title: "Leave comments", completed: true, position: 2 },
        { id: "s5", title: "Discuss with team", completed: false, position: 3 },
        { id: "s6", title: "Send final version", completed: false, position: 4 },
      ],
      categoryId: "product",
      startDate: daysFromNow(4),
      endDate: daysFromNow(4),
    },
    {
      id: "t6",
      title: "Water the plants",
      description: "",
      status: "todo",
      priority: "low",
      dueAt: daysFromNow(7),
      completedAt: null,
      position: 6,
      createdAt: m7.created,
      updatedAt: m7.updated,
      labelIds: [],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(7),
      endDate: daysFromNow(7),
    },
    {
      id: "t7",
      title: "Plan weekend trip",
      description: "Ideas so far: hiking trail, the new museum, or a day by the lake.",
      status: "todo",
      priority: "low",
      dueAt: daysFromNow(10),
      completedAt: null,
      position: 7,
      createdAt: m8.created,
      updatedAt: m8.updated,
      labelIds: ["personal"],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(10),
      endDate: daysFromNow(10),
    },
    {
      id: "t8",
      title: "Clean the room",
      description: "",
      status: "completed",
      priority: "medium",
      dueAt: daysFromNow(-2),
      completedAt: datetimeFromNow(-2, 16),
      position: 8,
      createdAt: m3.created,
      updatedAt: datetimeFromNow(-2, 16),
      labelIds: ["personal"],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(-2),
      endDate: daysFromNow(-2),
    },
    {
      id: "t9",
      title: "Book dentist appointment",
      description: "",
      status: "completed",
      priority: "none",
      dueAt: daysFromNow(-5),
      completedAt: datetimeFromNow(-5, 11),
      position: 9,
      createdAt: m9.created,
      updatedAt: datetimeFromNow(-5, 11),
      labelIds: ["personal"],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(-5),
      endDate: daysFromNow(-5),
    },
    {
      id: "t10",
      title: "Send invoice to Marta",
      description: "",
      status: "completed",
      priority: "high",
      dueAt: daysFromNow(-1),
      completedAt: datetimeFromNow(-1, 10),
      position: 10,
      createdAt: m10.created,
      updatedAt: datetimeFromNow(-1, 10),
      labelIds: ["work"],
      subtasks: [],
      categoryId: null,
      startDate: daysFromNow(-1),
      endDate: daysFromNow(-1),
    },

    {
      id: "p1",
      title: "Project Kickoff",
      description: "Align on scope, owners, and the first milestone.",
      status: "completed",
      priority: "high",
      dueAt: p1.due,
      completedAt: p2.iso,
      position: 11,
      createdAt: m4.created,
      updatedAt: p2.iso,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "product",
      ...span(1, 2),
    },
    {
      id: "p2",
      title: "Design Research",
      description: "Talk to five users and summarize the patterns we see.",
      status: "completed",
      priority: "medium",
      dueAt: p4.due,
      completedAt: p4.iso,
      position: 12,
      createdAt: m3.created,
      updatedAt: p4.iso,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "design",
      ...span(3, 4),
    },
    {
      id: "p3",
      title: "Technical Research",
      description: "Compare the two candidate approaches and pick one.",
      status: "todo",
      priority: "medium",
      dueAt: p4.due,
      completedAt: null,
      position: 13,
      createdAt: m2.created,
      updatedAt: m2.updated,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "development",
      ...span(3, 5),
    },
    {
      id: "p4",
      title: "UI Design",
      description: "Screens for the core flow, plus empty and error states.",
      status: "todo",
      priority: "high",
      dueAt: p9.due,
      completedAt: null,
      position: 14,
      createdAt: m1.created,
      updatedAt: m1.updated,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "design",
      ...span(5, 9),
    },
    {
      id: "p5",
      title: "Internal Review",
      description: "Walk through the plan with the team before building.",
      status: "completed",
      priority: "medium",
      dueAt: p7.due,
      completedAt: p7.iso,
      position: 15,
      createdAt: m2.created,
      updatedAt: p7.iso,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "product",
      ...span(6, 7),
    },
    {
      id: "p6",
      title: "Develop Project",
      description: "The main build. Progress tracked in subtasks.",
      status: "todo",
      priority: "high",
      dueAt: p16.due,
      completedAt: null,
      position: 16,
      createdAt: m1.created,
      updatedAt: m1.updated,
      labelIds: ["work"],
      subtasks: [
        { id: "s7", title: "Set up project", completed: false, position: 1 },
        { id: "s8", title: "Core feature", completed: false, position: 2 },
        { id: "s9", title: "Polish pass", completed: false, position: 3 },
      ],
      categoryId: "development",
      ...span(7, 16),
    },
    {
      id: "p7",
      title: "Prepare Operations",
      description: "Deployment plan, monitoring, and rollback steps.",
      status: "todo",
      priority: "medium",
      dueAt: p10.due,
      completedAt: null,
      position: 17,
      createdAt: m3.created,
      updatedAt: m3.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "operations",
      ...span(9, 10),
    },
    {
      id: "p8",
      title: "Design Review",
      description: "Round of feedback on the UI screens.",
      status: "todo",
      priority: "medium",
      dueAt: p12.due,
      completedAt: null,
      position: 18,
      createdAt: m4.created,
      updatedAt: m4.updated,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "design",
      ...span(11, 12),
    },
    {
      id: "p9",
      title: "Test Plan",
      description: "What we test, how, and who owns each area.",
      status: "todo",
      priority: "medium",
      dueAt: p13.due,
      completedAt: null,
      position: 19,
      createdAt: m5.created,
      updatedAt: m5.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "testing",
      ...span(12, 13),
    },
    {
      id: "p10",
      title: "Event Planning",
      description: "Launch event logistics — venue, invites, run of show.",
      status: "todo",
      priority: "low",
      dueAt: p14.due,
      completedAt: null,
      position: 20,
      createdAt: m6.created,
      updatedAt: m6.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "operations",
      ...span(13, 14),
    },
    {
      id: "p11",
      title: "Copywriting",
      description: "Landing page copy for launch.",
      status: "todo",
      priority: "low",
      dueAt: p17.due,
      completedAt: null,
      position: 21,
      createdAt: m7.created,
      updatedAt: m7.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "design",
      ...span(14, 17),
    },
    {
      id: "p12",
      title: "Test Case Design",
      description: "Turn the test plan into concrete cases.",
      status: "todo",
      priority: "medium",
      dueAt: p16.due,
      completedAt: null,
      position: 22,
      createdAt: m8.created,
      updatedAt: m8.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "testing",
      ...span(15, 16),
    },
    {
      id: "p13",
      title: "Team Sync",
      description: "Weekly check-in on progress and blockers.",
      status: "todo",
      priority: "none",
      dueAt: p15.due,
      completedAt: null,
      position: 23,
      createdAt: m9.created,
      updatedAt: m9.updated,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "product",
      ...span(15, 15),
    },
    {
      id: "p14",
      title: "Approve Budget",
      description: "Sign off on the remaining spend for the month.",
      status: "todo",
      priority: "high",
      dueAt: p15.due,
      completedAt: null,
      position: 24,
      createdAt: m10.created,
      updatedAt: m10.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "operations",
      ...span(15, 15),
    },
    {
      id: "p15",
      title: "API Integration",
      description: "Wire the frontend to the backend endpoints.",
      status: "todo",
      priority: "high",
      dueAt: p19.due,
      completedAt: null,
      position: 25,
      createdAt: m1.created,
      updatedAt: m1.updated,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "development",
      ...span(17, 19),
    },
    {
      id: "p16",
      title: "Landing Page QA",
      description: "Check every screen on mobile and desktop.",
      status: "todo",
      priority: "medium",
      dueAt: p20.due,
      completedAt: null,
      position: 26,
      createdAt: m2.created,
      updatedAt: m2.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "testing",
      ...span(19, 20),
    },
    {
      id: "p17",
      title: "Launch Checklist",
      description: "The final run through — every item must be checked.",
      status: "todo",
      priority: "urgent",
      dueAt: p21.due,
      completedAt: null,
      position: 27,
      createdAt: m3.created,
      updatedAt: m3.updated,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "operations",
      ...span(20, projectEnd),
    },
    {
      id: "p18",
      title: "Smoke Tests",
      description: "Happy-path pass right before launch.",
      status: "todo",
      priority: "high",
      dueAt: p22.due,
      completedAt: null,
      position: 28,
      createdAt: m4.created,
      updatedAt: m4.updated,
      labelIds: [],
      subtasks: [],
      categoryId: "testing",
      ...span(21, projectEnd),
    },
    {
      id: "p19",
      title: "Ship the launch page",
      description: "",
      status: "todo",
      priority: "urgent",
      dueAt: p17.due,
      completedAt: null,
      position: 29,
      createdAt: m5.created,
      updatedAt: m5.updated,
      labelIds: ["work"],
      subtasks: [],
      categoryId: "product",
      ...span(17, projectEnd),
    },
  ];
}
